import { StyleSheet } from "react-native";
import { ColorsButton } from "@/constants/ColorsButton";
import { Colors } from "@/constants/Colors";

export const stylesDashboard = StyleSheet.create({
    container: {
      flex: 1,
      height: "100%",
      width: "100%",
      backgroundColor: "#F2F4FE",
    },
    navBar: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      width: "100%",
      backgroundColor: "transparent",
      borderBottomWidth: 0.5,
      borderColor: ColorsButton.primary,
      paddingHorizontal: 20,
      paddingVertical: 15,
    },
    containerAll: {
      // borderWidth: 0.4,
      //borderColor: "#B78BFA",
      backgroundColor: "transparent",
      padding: 20,
      height: "100%",
      width: "100%",
      borderRadius: 15,
      gap: 10,
      justifyContent: "center",
    },
    inputStyle: {
      borderWidth: 0.5,
      borderColor: "#B78BFA",
      padding: 10,
      height: 40,
      width: "100%",
      borderRadius: 10,
      color: "#A7B5FF",
    },
    inputStyleError: {
      borderWidth: 0.5,
      borderColor: "#FF6B57",
      padding: 10,
      height: 40,
      width: "100%",
      borderRadius: 10,
      color: "#A7B5FF",
    },
    inputGroup: {
      gap: 15,
    },
    allButtons: {
      borderWidth: 0.5,
      borderColor: ColorsButton.primary,
      padding: 10,
      borderRadius: 10,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: "transparent",
    },
    logo: {
      justifyContent: "center",
      alignItems: "center",
      gap: 10,
    },
    studentLogo: {
        width: 30,
        height: 30
    },
    profileLogo: {
      width: 15,
      height: 15
    },
    imagesGroup:{
      width: 18,
      height: 18,
    },
    imagesGroupContent:{
      width: 22,
      height: 22,
    },
    contentCard: {
        padding: 15,
        backgroundColor: "transparent",
        gap: 25,
    },
    contentCardList: {
      padding: 15,
      backgroundColor: "transparent",
      gap: 5,
  },
    contentCardAdmin: {
      padding: 15,
      backgroundColor: "transparent",
      gap: 10,
      borderWidth: 0.5,
      borderColor: ColorsButton.warning,
      borderRadius: 10,
      flexDirection: "row",
  },
    contentSecurity: {
      backgroundColor: "transparent",
      gap: 25,
      paddingHorizontal: 20,
      paddingBottom: 20,
  },
    contentInfoUser: {
      paddingHorizontal: 20,
      paddingTop: 10,
      gap: 10,
      backgroundColor: "transparent",
  },
    shadowCard: {
      borderRadius: 5,
      width: "100%",
      padding: 15,
      gap: 10,
    },
    contentGroup: {
      justifyContent: "space-between",
      width: "100%",
      flexDirection: "row",
      alignItems: "center",
    },
    contentTitle: {
      flexDirection: "row",
      gap: 5,
      justifyContent: "center",
      alignItems: "center",
    },
    contentButton: {
      flexDirection: "row",
      gap: 10,
      justifyContent: "space-between",
      alignItems: "center",
      width: "100%",
    },
    contentButtonMaterias: {
      gap: 10,
      height: 130,
      justifyContent: "center",
      alignItems: "center",
      width: "100%",
    },
    Links: {
      borderWidth: 0.5,
      borderColor: ColorsButton.primary,
      padding: 10,
      borderRadius: 10,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: "transparent",
      width: "100%",
    },
    contentProfile: {
      flexDirection: "row",
      gap: 5,
      alignItems: "center",
      justifyContent: "flex-start",
    },
    contentInfoSecure: {
      justifyContent: "center",
      alignItems: "center",
      gap: 5,
      borderWidth: 0.3,
      borderColor: ColorsButton.primary,
      padding: 10,
      borderRadius: 10,
      backgroundColor: "transparent",
    },
    imgMaterias: {
      width: 35,
      height: 35,
    },
    ueRegister: {
      width: 50,
      height: 50,
    },
    ueRegisterContainer: {
      justifyContent: "center",
      alignItems: "center",
      padding: 15,
      gap: 10,
      width: "100%",
    },
    LinkInfo: {
      borderWidth: 0.5,
      borderColor: ColorsButton.primary,
      paddingVertical: 2,
      paddingHorizontal: 10,
      borderRadius: 20,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: "transparent",
    },
    imagesMateriaDetail: {
      width: 50,
      height: 50,
    },
    materiasDetailContainer: {
      justifyContent: "center",
      alignItems: "center",
      gap: 10,
      width: "100%",
    },
    nameMateriaDetail: {
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      gap: 2,
    },
    loadingView: {
      position: "absolute",
      backgroundColor: "rgba(0, 0, 0, 0.5)",
      width: "100%",
      height: "100%",
      justifyContent: "center",
      alignItems: "center",
      zIndex: 1,
    }
  });